apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: microservices
  labels:
    app: orders-service

spec:
  selector:
    app: orders-service

  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-v1
  namespace: microservices
  labels:
    app: orders-service
    version: v1

spec:
  replicas: 2

  selector:
    matchLabels:
      app: orders-service
      version: v1

  template:
    metadata:
      labels:
        app: orders-service
        version: v1

    spec:
      containers:
        - name: orders-service
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              value: "v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-v2
  namespace: microservices
  labels:
    app: orders-service
    version: v2

spec:
  replicas: 1

  selector:
    matchLabels:
      app: orders-service
      version: v2

  template:
    metadata:
      labels:
        app: orders-service
        version: v2

    spec:
      containers:
        - name: orders-service
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              value: "v2"